name = "aydinguvenemlak"          # Worker adı
compatibility_date = "2026-01-20" # Bugünkü tarih veya gelecekteki tarih
type = "javascript"               # veya "webpack", "modules" vs.

# Eğer static assets deploy edeceksen:
[site]
bucket = "./dist"
entry-point = "workers-site"
